import images from "./images.js";
const products = {
  frutales: [
    {
      name: "Melón",
      serial: "C. 2332",
      temp: "22°",
      cant: "6X700ML",
      src: images.botellas.frutales[0],
    },
    {
      name: "Frutilla",
      serial: "C. 2312",
      temp: "22°",
      cant: "6X700ML",
      src: images.botellas.frutales[1],
    },
    {
      name: "Curaçao Triple Sec",
      serial: "C. 2326",
      temp: "39°",
      cant: "6X700ML",
      src: images.botellas.frutales[2],
    },
    {
      name: "Blue Curaçao",
      serial: "C. 2328",
      temp: "29°",
      cant: "6X700ML",
      src: images.botellas.frutales[3],
    },
    {
      name: "Limoncello",
      serial: "C. 2325",
      temp: "29°",
      cant: "6X700ML",
      src: images.botellas.frutales[4],
    },
    {
      name: "Durazno",
      serial: "C. 2321",
      temp: "24°",
      cant: "6X700ML",
      src: images.botellas.frutales[5],
    },
    {
      name: "Kiwi",
      serial: "C, 2338",
      temp: "22°",
      cant: "6X700ML",
      src: images.botellas.frutales[6],
    },
    {
      name: "Manzana",
      serial: "C. 2320",
      temp: "22°",
      cant: "6X700ML",
      src: images.botellas.frutales[7],
    },
    {
      name: "Menta",
      serial: "C. 2315",
      temp: "24°",
      cant: "6X700ML",
      src: images.botellas.frutales[8],
    },
    {
      name: "Café",
      serial: "C. 2336",
      temp: "24°",
      cant: "6X700ML",
      src: images.botellas.frutales[9],
    },
    {
      name: "Cacao",
      serial: "C: 2309",
      temp: "24°",
      cant: "6X700ML",
      src: images.botellas.frutales[10],
    },
    {
      name: "Amaretto",
      serial: "C. 2319",
      temp: "24°",
      cant: "6X700ML",
      src: images.botellas.frutales[11],
    },
    {
      name: "Licor de Menta",
      serial: "C. 1466",
      temp: "24°",
      cant: "12X200ML",
      src: images.botellas.frutales[12],
    },
    {
      name: "Licor de Melón",
      serial: "C. 1469",
      temp: "22°",
      cant: "12X200ML",
      src: images.botellas.frutales[13],
    },
  ],
  cremosos: [
    {
      name: "Chocotella",
      serial: "C. 2346",
      temp: "17°",
      cant: "6X700ML",
      src: images.botellas,
    },
    {
      name: "Chocolate Amargo",
      serial: "C. 2345",
      temp: "17°",
      cant: "6X700ML",
      src: images.botellas,
    },
    {
      name: "Chocolate",
      serial: "C. 2306",
      temp: "17°",
      cant: "6X700ML",
      src: images.botellas,
    },
    {
      name: "Chocolate a la Frutilla",
      serial: "C. 2341",
      temp: "17°",
      cant: "6X700ML",
      src: images.botellas,
    },
    {
      name: "Chocolate al Dulce de Leche",
      serial: "C. 2330",
      temp: "17°",
      cant: "6X700ML",
      src: images.botellas,
    },
    {
      name: "Chocolate a la Almendra",
      serial: "C. 2323",
      temp: "17°",
      cant: "6X700ML",
      src: images.botellas,
    },
    {
      name: "Chocolate a la Menta",
      serial: "C. 2322",
      temp: "17°",
      cant: "6X700ML",
      src: images.botellas,
    },
    {
      name: "Chocolate Blanco",
      serial: "C, 2324",
      temp: "17°",
      cant: "6X700ML",
      src: images.botellas,
    },
    {
      name: "Dulce de Leche",
      serial: "C. 2316",
      temp: "17°",
      cant: "6X700ML",
      src: images.botellas,
    },
    {
      name: "Dulce de Leche a la Almendra",
      serial: "C. 2343",
      temp: "17",
      cant: "6X700ML",
      src: images.botellas,
    },
    {
      name: "Banana con Dulce de Leche",
      serial: "C. 2334",
      temp: "17°",
      cant: "6X700ML",
      src: images.botellas,
    },
    {
      name: "Huevo",
      serial: "C: 2305",
      temp: "18°",
      cant: "6X700ML",
      src: images.botellas,
    },
    {
      name: "Licor de Chocolate",
      serial: "C. 1465",
      temp: "17°",
      cant: "12X200ML",
      src: images.botellas,
    },
    {
      name: "Licor de Dulce de Leche",
      serial: "C. 1468",
      temp: "17°",
      cant: "12X200ML",
      src: images.botellas,
    },
  ],
};

export default products;
